In [2]:
import numpy as np
# don't change any function name write you all code inside the function only for every question solution and return you output as mentioned in problem statement.

### 1. Write a NumPy program to create an array of all the even integers from a to b(both inclusive).

Input: 4,10

Output: [4,6,8,10]

In [2]:
def question_first_solution(a,b):
    return list(np.arange(a,b+2,2))
question_first_solution(3,11)

[3, 5, 7, 9, 11]

### 2. Write a NumPy program to create a vector with values from a to b and change the sign of the numbers in the range from c to d.

Input: 0, 20, 9, 15

Output: [  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12, -13, -14, -15,  16,  17,  18,  19]

In [2]:
def question_second_solution(a,b,c,d):
    ary = np.arange(a,b)
    ary[(ary >= c) & (ary <= d)] *= -1
    return list(ary)
question_second_solution(0,20,9,15)

[0, 1, 2, 3, 4, 5, 6, 7, 8, -9, -10, -11, -12, -13, -14, -15, 16, 17, 18, 19]

### 3. Write a NumPy program to create a mxn matrix, in which the elements on the borders will be equal to 1, and inside 0.

Input: 3, 4

Output:

         [[1., 1., 1., 1.],

          [1., 0., 0., 1.],
          
          [1., 1., 1., 1.]]

In [10]:
def question_third_solution(m,n):
    arr = np.ones((m,n))
    arr[1:-1,1:-1]=0
    return arr
question_third_solution(3,4)

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])


### 4. Write a NumPy program to remove all rows in a NumPy array that contain non-numeric values.

Input: [[1,2,3], [4,5,np.nan], [7,8,9], [True, False, True]]

Output: [[1., 2., 3.],
         [7., 8., 9.],
         [1., 0., 1.]]

In [11]:
def question_fourth_solution(x):
    return x[~np.isnan(x).any(axis=1)]
    
question_fourth_solution(np.array([[1,2,3], [4,5,np.nan], [7,8,9], [True, False, True]]))

array([[1., 2., 3.],
       [7., 8., 9.],
       [1., 0., 1.]])

### 5. Write a NumPy program to select indices satisfying multiple conditions in a NumPy array.
Input:

a = np.array([97, 101, 105, 110, 109])

b = np.array([0, 1, 2, 3, 4])

Note: Select the elements from the second array corresponding to elements in the first array that are greater than 100 and less than 110

Output: [1, 2, 4]

In [12]:
def question_fifth_solution(a,b):
    return list(b[(100 < a ) & (a < 110)])

question_fifth_solution(np.array([97, 101, 105, 110, 109]),np.array([0, 1, 2, 3, 4]))

[1, 2, 4]

### 6. Write a NumPy program to count the frequency of unique values in numpy array.

Input: [10,10,20,10,20,20,20,30, 30,50,40,40]

Output: [3, 4, 2, 2, 1]

In [13]:
def question_sixth_solution(a):
    num,num1 = np.unique(a,return_counts= True)
    return list(num1) 
question_sixth_solution(np.array([10,10,20,10,20,20,20,30, 30,50,40,40]))

[3, 4, 2, 2, 1]


### 7. Write a NumPy program to search the index of a given array in another given array.

Input: [[1,2,3], [4,5,6] , [7,8,9], [10, 11, 12]], [1,2,3]

Output: [1]

In [16]:
def question_seventh_solution(array, test_array):
    return np.where((array == test_array).all(1))[0]
    
question_seventh_solution(np.array([[1,2,3], [4,5,6] , [7,8,9], [10, 11, 12]]), np.array([1,2,3]))

[0]


### 8. Write a NumPy program to sort a given complex array using the real part first, then the imaginary part.

Input: [1 + 2j, 3 - 1j, 3 - 2j, 4 - 3j, 3 + 5j]

Output: [1.+2.j, 3.-2.j, 3.-1.j, 3.+5.j, 4.-3.j]

In [20]:
def question_eighth_solution(array):
    return np.sort_complex(array)

question_eighth_solution(np.array([1 + 2j, 3 - 1j, 3 - 2j, 4 - 3j, 3 + 5j]))

array([1.+2.j, 3.-2.j, 3.-1.j, 3.+5.j, 4.-3.j])

### 9. Write a NumPy program to get the indices of the sorted elements of a given array.
Input: [1023, 5202, 6230, 1671, 1682, 5241, 4532]

Output: [0, 3, 4, 6, 1, 5, 2]

In [21]:
def question_ninth_solution(array):
    return list(np.argsort(array))

question_ninth_solution(np.array(np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])))

[0, 3, 4, 6, 1, 5, 2]

### 10. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

Output: [[0 1 0 1 0 1 0 1]                                                      
             [1 0 1 0 1 0 1 0]                                                      
             [0 1 0 1 0 1 0 1]                                                      
             [1 0 1 0 1 0 1 0]                                                      
             [0 1 0 1 0 1 0 1]                                                      
             [1 0 1 0 1 0 1 0]                                                      
             [0 1 0 1 0 1 0 1]                                                      
             [1 0 1 0 1 0 1 0]]

In [34]:
def question_tenth_solution():
    arr = np.zeros((8,8))
    arr[1::2,::2] = 1
    arr[::2,1::2] = 1
    return arr
    
question_tenth_solution()


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])